spring:
  h2:
    console:
      path: /db
      enabled: true
  datasource:
    url: jdbc:h2:file:./could-admin;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    rest:
      base-path: /api
  quartz:
    job-store-type: JDBC